name: Java CI with Gradle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Set JAVA_TOOL_OPTIONS
      run: echo "JAVA_TOOL_OPTIONS=-XX:+UseContainerSupport" >> $GITHUB_ENV

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: 8.10

    - name: Build with Gradle (without Wrapper)
      run: gradle build --stacktrace

    - name: Upload Test Report
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: build/reports/tests/

    - name: Display Test Report in Summary
      run: |
        echo "## Test Results" | tee -a $GITHUB_STEP_SUMMARY
        cat build/reports/tests/test/index.html | tee -a $GITHUB_STEP_SUMMARY || echo "Test report not found."
