name: Java CI with Gradle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Vérification du code
    - name: Checkout code
      uses: actions/checkout@v2

    # Installation de JDK (Java 17 ici, modifiable selon la version que tu veux utiliser)
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adoptopenjdk'

    # Mise en place de Gradle
    - name: Set up Gradle
      uses: gradle/wrapper-validation-action@v1

    # Compilation du projet avec Gradle
    - name: Build with Gradle
      run: ./gradlew build

    # Tester si tout fonctionne bien (facultatif si tu as des tests configurés)
    - name: Run tests
      run: ./gradlew test
